### ISSUE TITLE
Build conda package

### ISSUE THREAD

**Issue by pedroaugustosmribeiro** [laszukdawid/PyEMD#168]
Hi,

Thanks for the package and for publishing on PyPi.
Would you please also build and share a conda package of it, like on conda-forge?

I build it myself with the following recipe (file meta.yaml), feel free to review and use it:

```yaml
{% set name = "EMD-signal" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EMD-signal-{{ version }}.tar.gz
  sha256: fd20ec894205075625a1ae51bda53196afe0750118f4e606ba08b9653774cfd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - setuptools >=58
    - wheel
    - pip
  run:
    - python >=3.6,<4.0
    - numpy >=1.12
    - scipy >=0.19
    - pathos >=0.2.1
    - tqdm <5.0,>=4.64.0

test:
  imports:
    - PyEMD
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/laszukdawid/PyEMD
  summary: Implementation of the Empirical Mode Decomposition (EMD) and its variations
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - laszukdawid
```
